apiVersion: v1
kind: PersistentVolume
metadata:
  name: healthchecker-vol
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host-volume"